### ISSUE TITLE
libEGL warning: failed to find any driver

### ISSUE THREAD

**Issue by camel007** [caramelli/yagears#2]
As you tell in your ppt:
```
The Mesa 3D project makes OpenGL and OpenGL ES rendering possible using CPU operations only and the Linux Framebuffer (without requiring a GPU)
```
my device has arm a53 without gpu. I build mesa-7.11.2 and yagear
```
	Usage: ./test/yagears2 -b Backend -e Engine

		Backends: egl-fbdev

		Engines:  glesv1_cm
```
when i run `./test/yagears2 -b egl-fbdev -e glesv1_cm`, it gives me: 
```
libEGL warning: failed to find any driver
libEGL warning: failed to find any driver
eglInitialize failed: 0x3001
```

**Comment by caramelli** [comment]
Hi,

Be sure that:

  - EGL_PLATFORM is set to "fbdev"
  - the fbdev_create_sw_winsys() function of the src/gallium/winsys/sw/fbdev/fbdev_sw_winsys.c Mesa file is called when calling eglInitialize()

But yes, it can be tricky to have a Mesa version correctly built to work with EGL based on the fbdev platform. It would be easier if the fbdev platform was still maintained in Mesa (its support has been removed since version 10.6.0): I'm putting this on my TODO list.

**Comment by camel007** [comment]
Thank you! 
Finally, I run yagears1(EGL with fbdev) on my device successfully.
Share my configurations:

## environment:
1. arm53 without mali gpu. 
2. linux kernel 4.14  
3. mesa 7.11.2  
4. yagears-1 branch. 

## steps:  
1. before execute `./configure`,   should export CC, CXX. 
2. configuration for mesa: 

```shell
./configure --prefix=PREFIX --host=aarch64-unknown-linux-gnu --enable-debug --enable-gles1 --enable-gles2 --enable-egl --disable-gbm --enable-shared-glapi --with-egl-platforms=fbdev --with-gallium-drivers=swrast -enable-shared --disable-openvg --enable-gallium-egl --disable-xorg  --disable-glu --disable-glw --enable-opengl CFLAGS=-DMESA_EGL_NO_X11_HEADERS --disable-driglx-direct --with-driver=osmesa
```
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/4254753/157360596-31fe8d95-0e97-41fe-a5c1-e5fa8ea7fab5.png">

3. modify yagears1  
change the main.c as bellow
```c++
  if (!strcmp(backend, "egl-fbdev")) {
    egl_win = eglCreateWindowSurface(egl_dpy, egl_config, (EGLNativeWindowType)fb_win, NULL);
  }
```
to.  
```c++
  if (!strcmp(backend, "egl-fbdev")) {
    egl_win = eglCreateWindowSurface(egl_dpy, egl_config, (EGLNativeWindowType)0, NULL);
  }
```
if window is not zero, create window surface wiil fail. 
mesa has judegement logic in native_fbdev.c 
```C++
   /* there is only one native window: NULL */
   if (win)
      return NULL;
```

4. configuration for yagears1:  
```shell 
./configure --host=aarch64-linux-gnu --disable-gl --disable-gl-x11 --disable-gl-directfb --disable-gl-fbdev --disable-egl-x11 --disable-egl-directfb --disable-egl-wayland --disable-egl-drm --disable-egl-rpi --disable-egl-xcb --disable-qt --disable-gtk --disable-sfml --disable-png --with-sysroot=/xxxx/staging
```

**Comment by caramelli** [comment]
Great!

I now remember using EGL with the Linux Framebuffer on an embedded system but having a Mali GPU. The proprietary OpenGL implementation allowed to specify an EGLNativeWindowType when calling eglCreateWindowSurface() and I slightly modified the Mesa implementation in order to have the same possibility in Mesa.

But I should work on that again: I'd like to see fbdev platform support in Mesa again.
